export const PROMPTS = [
  'What is the capital of France?',
  'What do cows drink?',
  'What color is the sky on a clear day?',
  'What is 2 + 2?',
  'What do you call a baby dog?',
  'What is the largest planet in our solar system?',
  'What is the main ingredient in guacamole?',
  'How many days are in a week?',
  'What do fish live in?',
  'What is the fastest land animal?',
  'What language do people speak in Brazil?',
  'What do bees make?',
  'What is the opposite of hot?',
  'What do you use to brush your teeth?',
  'What is the freezing point of water in Fahrenheit?',
  'What do birds have that helps them fly?',
  'What is the name of the fairy in Peter Pan?',
  'What planet do we live on?',
  'What is the tallest animal?',
  'What do you call frozen water?',
  'How many legs does a spider have?',
  'What fruit is yellow and curved?',
  'What do you call a person who flies an airplane?',
  'What is the study of rocks called?',
  'What do plants need to grow besides water?',
  'What is the hardest natural substance?',
  "What animal is known as man's best friend?",
  'What do you call a shape with three sides?',
  'What color do you get when you mix red and blue?',
  'What is the smallest prime number?',
  'What is the chemical symbol for water?',
  'What galaxy do we live in?',
  'Who painted the Mona Lisa?',
  'What is the largest ocean on Earth?',
  'How many continents are there?',
  'What instrument has 88 keys?',
  'What is the currency of Japan?',
  'Who wrote Romeo and Juliet?',
  'What gas do plants breathe in?',
  'What is the speed of light?',
];

export function getRandomPrompt(): string {
  return PROMPTS[Math.floor(Math.random() * PROMPTS.length)];
}
